#!/bin/bash

# Commands
DATE="$(command -vp date)"

# Global variables
PROG_NAME="$(basename "${0}")"
HARDWARE_ALL=" \
	n6gq \
	n6gsdl \
	solidsense \
"
IMAGE_SUFFIX=" \
	manifest \
	mender \
	mender.bmap \
	tar.gz \
"
CONFIG_FILE="meta-cip-sr-common/scripts/build.conf"

# initialize configuration array
declare -A config
config=(
	[devices]="n6gq n6gsdl solidsense"
	[product]=Solidsense
	[release]=dev
	[date]=$("${DATE}" "+%Y%m%d")
	[iteration]=00
	[variant]=""
	[mender_artifact]=/home/eric/bin/mender-artifact
	[mender_private_key_file]=/home/eric/work.kingcheese/Solidrun/solidsense/signing-private-keys/private.key
	[mender_public_key_file]=/home/eric/work.kingcheese/Solidrun/solidsense/signing-private-keys/public.key
	[mender_server_url]=https://mender.solidsense.io
)

# Pretty print
NC="\\e[0m"
BOLD="\\e[1m"
#BLINK="\\e[5m"
UNDERLINED="\\e[4m"
RED="\\e[31m"
YELLOW="\\e[33m"
LIGHT_RED="\\e[91m"
LIGHT_GREEN="\\e[92m"

# functions
usage () {
	echo "${PROG_NAME}:"
	echo "    -H|--hardware <hardware type>                 :default is <all>"
	echo "    -p|--product <product>                        :default is <${config[product]}>"
	echo "    -r|--release <release version>                :default is <${config[release]}>"
	echo "    -d|--date <date>                              :default is <${config[date]}>"
	echo "    -i|--iteration <iteration>                    :default is <${config[iteration]}>"
	echo "    -v|--variant <variant>                        :default is no specific variant"
	echo "    -c|--config <config>                          :default is <${CONFIG_FILE}>"
	echo "    -h|--help"
	echo ""
	exit 1
}

read_config_file () {
	if [ ! -f "${CONFIG_FILE}" ]; then
		echo "Config file <${CONFIG_FILE}> not found!"
		exit 1
	fi
	while read -r line ; do
		if echo "${line}" | grep -F = &>/dev/null; then
			varname=$(echo "${line}" | cut -d '=' -f 1)
			config[$varname]=$(echo "${line}" | cut -d '=' -f 2-)
		fi
	done < "${CONFIG_FILE}"
}

override_config_file_values () {
	if [ -n "${DEVICES}" ]; then
		config[devices]="${DEVICES}"
	fi
	if [ -n "${PRODUCT}" ]; then
		config[product]="${PRODUCT}"
	fi
	if [ -n "${RELEASE}" ]; then
		config[release]="${RELEASE}"
	fi
	if [ -n "${RELEASE_DATE}" ]; then
		config[date]="${RELEASE_DATE}"
	fi
	if [ -n "${ITERATION}" ]; then
		config[iteration]="${ITERATION}"
	fi
	if [ -n "${VARIANT}" ]; then
		config[variant]="${VARIANT}"
	fi
}

find_variant () {
	variant="${1}"
	case "${variant}" in
		maersk )
			echo "M"
			;;
		test )
			echo "T"
			;;
		[[:alpha:]]* )
			echo "${variant}" | cut --bytes=1 | tr '[:lower:]' '[:upper:]'
			;;
		* )
			echo ""
			;;
	esac
}

calc_duration () {
	time_start="${1}"
	time_end="${2}"

	echo $((time_end-time_start)) | awk '{printf("%02d:%02d:%02d\n", int($1/3600), int($1/60%60), int($1%60))}'
}

do_build () {
	if [ ! -d "deploy/logs/${VERSION}" ]; then
		mkdir -p "deploy/logs/${VERSION}"
	fi
	printf "\\nBuilding version ${LIGHT_GREEN}%s${NC}\\n" "${VERSION}"
	for device in ${config[devices]}; do
		START="$(${DATE} +%s)"
		log="deploy/logs/${VERSION}/build-${device}-$(${DATE} +%Y%m%d-%H:%M)"
		# determine variant
		if [ -n "${VARIANT}" ]; then
			if [ "${VARIANT}" = "test" ]; then
				main_yml="kas-solidsense.yml"
			else
				main_yml="kas-solidsense-${VARIANT}.yml"
			fi
		else
			main_yml="kas-solidsense.yml"
		fi
		if [ ! -f "${main_yml}" ]; then
			printf "\\nError file <%s> not found!\\n" "${main_yml}"
			exit 1
		fi
		# check if device yaml exists
		device_yml="meta-cip-sr-${device}/kas-${device}.yml"
		if [ ! -f "${device_yml}" ]; then
			printf "\\nError file <%s> not found!\\n" "${device_yml}"
			exit 1
		fi
		# Build using KAS
		printf "    MENDER_ARTIFACT_NAME=%s MENDER_SERVER_URL=%s kas build %s:%s\\n" \
			"${VERSION}" "${config[mender_server_url]}" "${main_yml}" "${device_yml}"
		printf "        ${LIGHT_RED}%s${NC} logging to ${BOLD}%s${NC}" \
			"${device}" \
			"${log}"
		MENDER_ARTIFACT_NAME="${VERSION}" MENDER_SERVER_URL="${config[mender_server_url]}" \
			kas build "${main_yml}":"${device_yml}" > "${log}" 2>&1
		ret="${?}"
		END="$(${DATE} +%s)"
		duration="$(calc_duration "${START}" "${END}")"
		if [ "${ret}" -eq "1" ] ; then
			printf " ${YELLOW}(%s)${NC} Error!: (%s)\\n" "${duration}" "${ret}"
		else
			printf " ${YELLOW}(%s)${NC}\\n" "${duration}"
		fi
		printf "\\n"
	done
}

do_update_manifest () {
	MANIFEST_FILE="${1}"
	LICENSE_DIR="${2}"

	while read -r pkg rest ; do
		case "${pkg}" in
			kernel-* )
					echo "${pkg} ${rest} <GPL>"
				;;
			*-dev )
				#license_pkg="$(echo "$pkg" | sed 's/-dev//')"
				license_pkg="${pkg//-dev//}"
				if [ -d "${LICENSE_DIR}/${license_pkg}" ] ; then
					RECIPE_INFO="${LICENSE_DIR}/${license_pkg}/recipeinfo"
					license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
					echo "${pkg} ${rest} <${license}>"
				else
					echo "${pkg} ${rest} UNKNOWN"
				fi
				;;
			*-*-* )
				if [ -d "${LICENSE_DIR}/${pkg}" ] ; then
					RECIPE_INFO="${LICENSE_DIR}/${pkg}/recipeinfo"
					license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
					echo "${pkg} ${rest} <${license}>"
				else
					license_pkg="$(echo "${pkg}" | awk '{gsub("-", " "); print $1"-"$2}')"
					if [ -d "${LICENSE_DIR}/${license_pkg}" ] ; then
						RECIPE_INFO="${LICENSE_DIR}/${license_pkg}/recipeinfo"
						license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
						echo "${pkg} ${rest} <${license}>"
					else
						license_pkg="$(echo "${pkg}" | awk '{gsub("-", " "); print $1}')"
						if [ -d "${LICENSE_DIR}/${license_pkg}" ] ; then
							RECIPE_INFO="${LICENSE_DIR}/${license_pkg}/recipeinfo"
							license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
							echo "${pkg} ${rest} <${license}>"
						else
							echo "${pkg} ${rest} UNKNOWN"
						fi
					fi
				fi
				;;
			*-* )
				if [ -d "${LICENSE_DIR}/${pkg}" ] ; then
					RECIPE_INFO="${LICENSE_DIR}/${pkg}/recipeinfo"
					license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
					echo "${pkg} ${rest} <${license}>"
				else
					license_pkg="$(echo "${pkg}" | awk '{gsub("-", " "); print $1}')"
					if [ -d "${LICENSE_DIR}/${license_pkg}" ] ; then
						RECIPE_INFO="${LICENSE_DIR}/${license_pkg}/recipeinfo"
						license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
						echo "${pkg} ${rest} <${license}>"
					else
						echo "${pkg} ${rest} UNKNOWN"
					fi
				fi
				;;
			* )
				if [ -d "${LICENSE_DIR}/${pkg}" ] ; then
					RECIPE_INFO="${LICENSE_DIR}/${pkg}/recipeinfo"
					license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
					echo "${pkg} ${rest} <${license}>"
				else
					echo "${pkg} ${rest} UNKNOWN"
				fi
				;;
		esac
	done < "${MANIFEST_FILE}"
}

do_deploy_images () {
	dir_deploy="deploy/${VERSION}"

	if [ ! -d "${dir_deploy}" ]; then
		mkdir -p "${dir_deploy}"
	fi

	printf "Copying over images for${LIGHT_RED}%s${NC}\\n"

	# Copy over the licenses
	START="$(${DATE} +%s)"
	printf "    ${RED}%s${NC}" "licenses"
	rsync -avz build/tmp/deploy/licenses "${dir_deploy}" > /dev/null 2>&1
	CWD="$(pwd)"
	cd "${dir_deploy}" || exit
	zip -9 -r "${VERSION}-licenses.zip" "licenses" > /dev/null 2>&1
	cd "${CWD}" || exit
	END="$(${DATE} +%s)"
	duration="$(calc_duration "${START}" "${END}")"
	printf " ${YELLOW}(%s)${NC}\\n" "${duration}"

	for device in ${config[devices]}; do
		image_prefix_src="build/tmp/deploy/images/${device}/core-image-minimal-${device}"
		image_prefix_dst="${dir_deploy}/${device}-core-image-minimal-${VERSION}"

		if [ ! -d "${dir_deploy}" ]; then
			mkdir -p "${dir_deploy}"
		fi

		# Copy over images
		printf "    ${RED}%s${NC}" "${device}"
		START="$(${DATE} +%s)"
		for suffix in ${IMAGE_SUFFIX}; do
			if [ -f "${image_prefix_src}.${suffix}" ]; then
				cp "${image_prefix_src}.${suffix}" "${image_prefix_dst}.${suffix}"
			else
				printf "\\n\\n${RED}Error: ${NC} %s not found!" "${image_prefix_src}.${suffix}"
				exit 1
			fi
		done

		# Update manifest file
		do_update_manifest "${image_prefix_src}.manifest" "${dir_deploy}/licenses" > "${image_prefix_dst}.manifest.lic"

		END="$(${DATE} +%s)"
		duration="$(calc_duration "${START}" "${END}")"
		printf " ${YELLOW}(%s)${NC}\\n" "${duration}"
	done

	printf "\\n"
}

do_deploy_sign_artifact () {
	if [ ! -d "deploy/${VERSION}" ]; then
		mkdir -p "deploy/${VERSION}"
	fi
	printf "Signing and verifying artifact for${LIGHT_RED}%s${NC}\\n"
	for device in ${config[devices]}; do
		dir_deploy="deploy/${VERSION}"
		mender_artifact="${dir_deploy}/${device}-core-image-minimal-${VERSION}.mender"

		if [ ! -d "${dir_deploy}" ]; then
			mkdir -p "${dir_deploy}"
		fi

		# Sign and verify artifacts
		printf "    ${RED}%s${NC}" "${device}"
		START="$(${DATE} +%s)"
		${config[mender_artifact]} sign --key "${config[mender_private_key_file]}" "${mender_artifact}"
		${config[mender_artifact]} validate --key "${config[mender_public_key_file]}" "${mender_artifact}" > /dev/null 2>&1
		END="$(${DATE} +%s)"
		duration="$(calc_duration "${START}" "${END}")"
		printf " ${YELLOW}(%s)${NC}\\n" "${duration}"
	done
}

# main

options=$(getopt -l "help,hardware:,product:,release:,date:,iteration:,variant:,config:" -o "hH:p:r:d:i:v:c:" -- "${@}")
eval set -- "${options}"

while true
do
	case "${1}" in
		-h|--help )
			usage
			;;
		-H|--hardware )
			shift
			if [ "${1}" = "all" ]; then
				DEVICES="${HARDWARE_ALL}"
			else
				DEVICES="${1//,/' '}"
			fi
			;;
		-p|--product )
			shift
			PRODUCT="${1}"
			;;
		-r|--release )
			shift
			RELEASE="${1}"
			;;
		-d|--date )
			shift
			RELEASE_DATE="${1}"
			;;
		-i|--iteration )
			shift
			ITERATION="$(printf "%02d" "$(( 10#${1}))")"
			;;
		-v|--variant )
			shift
			VARIANT="${1}"
			VARIANT_VER="$(find_variant "${1}")"
			;;
		-c|--config )
			CONFIG_FILE="${1}"
			;;
		\? )
			usage
			;;
		: )
			echo "Invalid option: ${OPTARG} requires an argument" 1>&2
			;;
		-- )
			shift
			break
			;;
		* )
			usage
			;;
	esac
	shift
done

# Read in the config file
read_config_file

# Override config file values with option values
override_config_file_values

if [ "${#}" -ne "0" ]; then
	usage
else
	if [ ! -d "meta-cip-sr-common" ]; then
		echo "Cannot find meta-cip-sr-common"
		exit 1
	fi
	FULL_START="$(${DATE} +%s)"
	if [ -n "${VARIANT_VER}" ] ; then
		VERSION="${config[product]}-${VARIANT_VER}${config[release]}-${config[date]}${config[iteration]}"
	else
		VERSION="${config[product]}-${config[release]}-${config[date]}${config[iteration]}"
	fi
	do_build
	do_deploy_images
	do_deploy_sign_artifact
	FULL_END="$(${DATE} +%s)"
	duration="$(calc_duration "${FULL_START}" "${FULL_END}")"
	printf "\\nThat entire run took ${BOLD}${UNDERLINED}%s${NC}.\\n\\n" "${duration}"
fi
