#!/bin/sh

# globals
PROG_NAME="$(basename "${0}")"
BB1_TMPFILE=""
BRANCH=""
FIND_REGEX="SolidSense-V1"
UPDATE_GIT=0

# functions
usage () {
	echo "${PROG_NAME}: <SRC_REV>"
	echo "    -h|--help"
	echo "    -b|--branch <branch>"
	echo "    -r|--regex <regex>			:default is <SolidSense-V1>"
	echo ""
	exit 1
}

find_files_to_update () {
	find . -type f -name \*bb\* -exec grep -q "${FIND_REGEX}" {} \; -print
}

# main

options=$(getopt -l "help,branch:,regex:" -o "hb:r:" -- "${@}")
eval set -- "${options}"

while true
do
	case "${1}" in
		-h|--help )
			usage
			;;
		-b|--branch )
			shift
			BRANCH="${1}"
			;;
		-r|--regex )
			shift
			FIND_REGEX="${1}"
			;;
		\? )
			usage
			;;
		: )
			echo "Invalid option: ${OPTARG} requires an argument" 1>&2
			;;
		-- )
			shift
			break
			;;
		* )
			usage
			;;
	esac
	shift
done

if [ "${#}" -ne "1" ]; then
	usage
else
	SRCREV="${1}"
	for bb_file in $(find_files_to_update); do
		if echo "${bb_file}" | grep -q swp; then
			continue
		fi
		echo "Updating: ${bb_file}"
		BB1_TMPFILE="$(mktemp /tmp/bb_tmpfile1.XXXXXX)"
		awk -v FIND_REGEX="${FIND_REGEX}" -v BRANCH="${BRANCH}" -v SRCREV="${SRCREV}" \
		'BEGIN {
		}
		{
			if (BRANCH)
			{
				if ($0 ~ ".*git.*"FIND_REGEX)
				{
					if (gsub(/;branch=[[:alnum:]\.]+;/, ";branch="BRANCH";", $0))
					{
						print $0
					} else {
						print $0
					}
					next
				}
			}
			if ($0 ~ "^SRCREV_"FIND_REGEX)
			{
				print "SRCREV_"FIND_REGEX" = \""SRCREV"\""
				next
			}
			print $0
		}' < "${bb_file}" > "${BB1_TMPFILE}"
		mv "${BB1_TMPFILE}" "${bb_file}"
		if [ "${UPDATE_GIT}" = "1" ]; then
			git commit -m "$(basename "${bb_file}"): update git branch/SRCREV" "${bb_file}"
		fi
	done
fi
